name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧱 Optional: if your HTML is in a subfolder like "public" or "dist"
      # If index.html is at root, remove this step.
      - name: Move site files
        run: |
          mkdir public
          cp index.html public/
          # Uncomment next line if you have CSS or images
          # cp -r style.css assets/ public/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public   # this folder must contain index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
